### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by bmatson** [OpenGarage/OpenGarage-App#4]
It appears that all the interface to Blynk is getting looped through the opengarage.io wordpress site (including the secret token to remotely control the device).

Is there some reason for not using the Blynk REST api directly from the app?  Inserting another actor (especially one implemented in Wordpress) in the middle of this communication is not a good idea IMHO.

**Comment by salbahra** [comment]
The Blynk API does not have SSL available and HTTP CORS are not allowed on iOS in Cordova based applications. This is the reason for using our server as a proxy.

**Comment by bmatson** [comment]
While it isn't ideal, according to the docs on Blynk they do have a SSL interface, it just uses a self-signed cert,, and according to this you can accept self-signed certs for a specific site in a cordova app... http://ivancevich.me/articles/ignoring-invalid-ssl-certificates-on-cordova-android-ios/

**Comment by rayshobby** [comment]
My understanding is that Blynk RESTful API doesn't support SSL:
http://docs.blynkapi.apiary.io/#

**Comment by salbahra** [comment]
There is really no reason for a self signed certificate at this point in time. Furthermore, the current workflow for packaging the app does not allow for code modification suggested by your link @bmatson. I don't think this will change in the short term however if Blynk adds proper SSL support we can consider changing this in the future.

**Comment by bmatson** [comment]
@rayshobby, I just tested it, they support SSL, it just uses a self-signed cert....
